version: '3'

services:
  postgres:
    image: 'postgres:11.5'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=rice-and-beans'
      - 'POSTGRES_PASSWORD=1234567'
    expose:
      - '5432'
    ports:
      - '5432:5432'
